/**
 * Mock mode controlling which mock-only features are active
 * - `dev`: all mock features enabled (status override, artificial latency)
 * - `strict`: clean REST simulation, mock features disabled
 */
export type MockMode = 'strict' | 'dev';

/**
 * TS-Mock-Proxy server configuration
 */
export interface ServerConfig {
  /** Path to the directory containing TypeScript type definitions */
  typesDir: string;

  /** Server port */
  port: number;

  /** Simulated latency (min-max in milliseconds) */
  latency?: {
    min: number;
    max: number;
  };

  /** Enable file hot-reload */
  hotReload: boolean;

  /** Enable schema caching */
  cache: boolean;

  /** Verbose mode for logging */
  verbose: boolean;

  /**
   * Mock mode: 'dev' (default) enables all mock features; 'strict' disables them.
   * Resolution order: CLI > MOCK_API_MODE env var > config file > default ('dev')
   */
  mockMode?: MockMode;

  /** Enable/disable write HTTP methods (POST, PUT, PATCH, DELETE). All enabled by default. */
  writeMethods?: {
    post?: boolean;
    put?: boolean;
    patch?: boolean;
    delete?: boolean;
  };

  /**
   * Path to persist mock data to a JSON file (absolute or relative to CWD).
   * Set to false or leave undefined to disable persistence (default).
   * Recommended value when enabled: '.mock-data.json'
   */
  persistData?: string | false;
}

/**
 * Interface metadata with endpoint flag information
 */
export interface InterfaceMetadata {
  /** Interface name */
  name: string;

  /** Whether the interface has the // @endpoint flag */
  hasEndpointFlag: boolean;
}

/**
 * Parsed TypeScript schema cached
 */
export interface ParsedSchema {
  /** Interface name */
  interfaceName: string;

  /** Source file path */
  filePath: string;

  /** Schema generated by Intermock */
  schema: Record<string, unknown>;

  /** Timestamp of last update */
  lastUpdated: number;
}

/**
 * Result of the mapping between a route and a type
 */
export interface RouteTypeMapping {
  /** Name of the type found */
  typeName: string;

  /** Indicates if the route requests an array */
  isArray: boolean;

  /** File containing the type */
  filePath?: string;
}

/**
 * Standard error response structure returned by all routes
 */
export interface ApiErrorResponse {
  error: string;
  message: string;
  hint?: string;
}

/**
 * Options for mock generation
 */
export interface MockGenerationOptions {
  /** Number of elements if it's an array */
  arrayLength?: number;

  /** Seed for random generation (reproducibility) */
  seed?: number;
}

export type WriteMethod = 'post' | 'put' | 'patch' | 'delete';
