/**
 * TS-Mock-Proxy server configuration
 */
export interface ServerConfig {
  /** Path to the directory containing TypeScript contracts */
  contractsDir: string;

  /** Paths to external directories (projects or repos) */
  externalDirs?: string[];

  /** Server port */
  port: number;

  /** Real backend URL for proxy mode (optional) */
  targetUrl?: string;

  /** Simulated latency (min-max in milliseconds) */
  latency?: {
    min: number;
    max: number;
  };

  /** Enable file hot-reload */
  hotReload: boolean;

  /** Enable schema caching */
  cache: boolean;

  /** Verbose mode for logging */
  verbose: boolean;
}

/**
 * Parsed TypeScript schema cached
 */
export interface ParsedSchema {
  /** Interface name */
  interfaceName: string;

  /** Source file path */
  filePath: string;

  /** Schema generated by Intermock */
  schema: Record<string, unknown>;

  /** Timestamp of last update */
  lastUpdated: number;
}

/**
 * Result of the mapping between a route and a type
 */
export interface RouteTypeMapping {
  /** Name of the type found */
  typeName: string;

  /** Indicates if the route requests an array */
  isArray: boolean;

  /** File containing the type */
  filePath?: string;
}

/**
 * Options for mock generation
 */
export interface MockGenerationOptions {
  /** Number of elements if it's an array */
  arrayLength?: number;

  /** Seed for random generation (reproducibility) */
  seed?: number;
}
